language: cpp
compiler: clang
before_install:
    - sudo apt-get install python-ply
    - wget -q https://launchpad.net/ubuntu/+archive/primary/+files/cxxtest_4.4-1_all.deb
    - sudo dpkg -i cxxtest_4.4-1_all.deb
env: CXXTEST=/usr/include
script: make test-valgrind
