language: cpp
compiler: clang
before_install:
    - echo | sudo apt-add-repository ppa:dhart/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq cxxtest
env: CXXTEST=/usr/include    
script: make test-valgrind
