language: cpp
compiler: clang
before_install:
    - sudo apt-get install python
    - wget -q https://launchpad.net/ubuntu/+archive/primary/+files/cxxtest_4.4-1_all.deb
    - sudo dpkg -i cxxtest_4.4-1_all.deb
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq g++-4.9
    - sudo apt-get install -qq valgrind
env: CXXTEST=/usr/include
script:
    - make test-valgrind
    - make -C assembler test
